version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=saif
    networks:
      - commun
    volumes:
      - ./mysql:/var/lib/mysql
  back:
    build: ./plateforme
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/users?autoReconnect=true&useSSL=false
    networks:
      - commun
    depends_on:
      - mysqldb
  front:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - commun
    depends_on:
      - back  
networks:
  commun: